"""Init

Revision ID: 59694352b1a6
Revises: 832c37b3d392
Create Date: 2023-07-28 11:20:54.619469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59694352b1a6'
down_revision = '832c37b3d392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('public_id', sa.String(length=150), nullable=False))
    op.add_column('images', sa.Column('image_name', sa.String(length=150), nullable=False))
    op.alter_column('images', 'description',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('images', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('images', 'description',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('images', 'image_name')
    op.drop_column('images', 'public_id')
    # ### end Alembic commands ###
