"""add_role

Revision ID: 832c37b3d392
Revises: 513ecc3dab80
Create Date: 2023-07-24 16:09:35.859157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832c37b3d392'
down_revision = '513ecc3dab80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True, default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute('DROP TYPE role')
    # ### end Alembic commands ###
