"""'user_information'

Revision ID: 8f6bccb1ef10
Revises: b196585885b0
Create Date: 2023-07-28 21:15:54.822224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6bccb1ef10'
down_revision = 'b196585885b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('information', sa.String(), nullable=True))
    op.add_column('users', sa.Column('number_of_images', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('average_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'average_rating')
    op.drop_column('users', 'number_of_images')
    op.drop_column('users', 'information')
    # ### end Alembic commands ###
