"""'new_images'

Revision ID: 9df648d2a241
Revises: 8f6bccb1ef10
Create Date: 2023-07-29 12:58:21.952338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df648d2a241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('public_id', sa.String(length=150), nullable=True))
    op.add_column('images', sa.Column('image_name', sa.String(length=150), nullable=True))
    op.drop_column('images', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('images', 'image_name')
    op.drop_column('images', 'public_id')
    # ### end Alembic commands ###
