"""add_logout

Revision ID: b196585885b0
Revises: 832c37b3d392
Create Date: 2023-07-27 22:43:56.828158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b196585885b0'
down_revision = '832c37b3d392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_black_list',
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('access_token')
    )
    op.alter_column('images', 'description',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'description',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_table('token_black_list')
    # ### end Alembic commands ###
